rootProject.name = "boot"
include("bbootimg")
include("aosp:boot_signer")
include("aosp:mkbootfs.10")
include("aosp:mkbootfs.11")
include("aosp:libsparse:base")
include("aosp:libsparse:sparse")
include("aosp:libsparse:img2simg")
include("aosp:libsparse:simg2img")
include("aosp:libsparse:simg2simg")
include("aosp:libsparse:append2simg")
include("aosp:libavb1.1")
include("aosp:libavb1.2")
include("avbImpl")
include("helper")
